export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_FETCH_SUCCESSED = 'SINGNUP_FETCH_SUCCEESSED';

export const INFO_START = 'INFO_START';
export const INFO_SUCCESSED = 'INFO_SUCCESSED';

export const GET_STOCKS_START = 'GET_STOCKS_START';
export const GET_STOCKS_SUCCESSED = 'GET_STOCKS_SUCCESSED';

